# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

name: docs
on:
  # for testing
  # workflow_dispatch:
  # testing branches
  # push:
  #   branches:
  #     - feature-refactor
  # schedule:
  #   # - cron: '0 1 * * THU'
  #   - cron: '0 1 * * *'
  pull_request:
    branches:
      - main

env:
  TEST_ANSIBLE_SOLACE_COLLECTION_DIR: "src/ansible_collections/solace/pubsub_plus"
  DOCS_MAKE_SCRIPT: "test-runner/run.make.docs.sh"
  TEST_RUNNER_LOGS_DIR: docs-logs

jobs:
  docs_test:
    # runs-on: ubuntu-18.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.8' ]
        ansible-version: [ 'ansible>=2.10.3,<2.11' ]
    steps:
      - name: Check Auth
        if: github.event_name == 'workflow_dispatch' && github.actor != 'ricardojosegomezulmke'
        run: |
          echo "not authorized"
          echo '::set-output name=IS_AUTHORIZED::false'
        id: auth
      - name: Cancel Workflow
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: setup python matrix version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible and collection dependencies
        env:
          ANSIBLE_VERSION: "${{ matrix.ansible-version }}"
        run: |
          python -m pip install --upgrade pip
          pip install "$ANSIBLE_VERSION"

      - name: Build and install collection
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          ansible-galaxy collection build .
          ansible-galaxy collection install *.gz

      - name: Install docs make dependencies
        run: |
          pip install -r devel/devel.requirements.txt

      - name: Make docs
        run: |
          export PROJECT_HOME="$GITHUB_WORKSPACE"
          export LOG_DIR="$GITHUB_WORKSPACE/${TEST_RUNNER_LOGS_DIR}"
          export RUN_FG=true
          ./${DOCS_MAKE_SCRIPT}

      - name: Check HTML dir
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          cd docs/build/html
          ls -la

###
# The End.
