# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

name: publish release
on:
  # for testing
  workflow_dispatch:

  release:
    types: [created]

env:
  DEBUG_FLAG: ${{ true }}
  TEST_ANSIBLE_SOLACE_COLLECTION_DIR: "src/ansible_collections/solace/pubsub_plus"
  DOCS_MAKE_SCRIPT: "test-runner/run.make.docs.sh"
  TEST_RUNNER_LOGS_DIR: publish-logs
  TEST_TEST_RUNNER_LOGS_NAME: test-runner-publish-logs

jobs:
  publish_release:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.8' ]
        ansible-version: [ 'ansible>=2.10.3,<2.11' ]
    steps:
      - name: Check Auth
        if: github.event_name == 'workflow_dispatch' && github.actor != 'ricardojosegomezulmke'
        run: |
          echo "not authorized"
          echo '::set-output name=IS_AUTHORIZED::false'
        id: auth
      - name: Cancel Workflow
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Checkout Current Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: setup python matrix version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ansible and collection dependencies
        env:
          ANSIBLE_VERSION: "${{ matrix.ansible-version }}"
        run: |
          python -m pip install --upgrade pip
          pip install "$ANSIBLE_VERSION"

      - name: Build and install collection
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          ansible-galaxy collection build .
          ansible-galaxy collection install *.gz

      - name: Install docs make dependencies
        run: |
          pip install -r devel/devel.requirements.txt
          # pip install --upgrade jinja2==2.11.2
          # echo ">>>>> jinja2"
          # pip show jinja2

      - name: Make docs
        run: |
          export PROJECT_HOME="$GITHUB_WORKSPACE"
          export LOG_DIR="$GITHUB_WORKSPACE/${TEST_RUNNER_LOGS_DIR}"
          export RUN_FG=true
          ./${DOCS_MAKE_SCRIPT}

      - name: Check HTML dir
        if: env.DEBUG_FLAG == 'true'
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          cd docs/build/html
          ls -la

      - name: Publish gh-pages
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages gh-pages
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          rsync -av ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}/docs/build/html/ gh-pages/
          cd gh-pages
          git add -A
          git commit --allow-empty -F ../generated.txt
          # git push -f -u origin gh-pages
          git push -u origin gh-pages

      - name: Publish collection
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          ansible-galaxy collection publish *.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN --import-timeout 300

      - name: Archive logs
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED != 'false' && github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_TEST_RUNNER_LOGS_NAME }}
          path: ${{ github.workspace }}/${{ env.TEST_RUNNER_LOGS_DIR }}
          if-no-files-found: error
###
# The End.
